import os
import shutil
import json


def read_template(template_path):

    with open(template_path, "r", encoding="utf-8") as file:

        return file.read()


def create_project(

    project_name: str,

    frontend: str,

    backend: str,

    database: str,

    project_type: str

):

    BASE_DIR = os.path.dirname(
        os.path.abspath(__file__)
    )

    project_path = os.path.join(

        BASE_DIR,

        "generated_projects",

        project_name

    )

    os.makedirs(

        project_path,

        exist_ok=True

    )

    folders = [

        "frontend",

        "backend",

        "backend/routes",

        "backend/models",

        "backend/schemas",

        "backend/utils"

    ]

    for folder in folders:

        os.makedirs(

            os.path.join(
                project_path,
                folder
            ),

            exist_ok=True

        )

    # README FILE

    readme_path = os.path.join(

        project_path,

        "README.md"

    )

    with open(readme_path, "w", encoding="utf-8") as file:

        file.write(

f'''# {project_name}

Generated by DevForge


## Project Type

{project_type}


## Tech Stack

Frontend: {frontend}

Backend: {backend}

Database: {database}


## Backend Setup

### FastAPI

pip install -r requirements.txt

uvicorn main:app --reload


## Frontend Setup

npm install

npm run dev


## Environment Variables

Check the .env file and update the required values.


## Generated Features

- Dynamic Project Generation
- ZIP Packaging
- Environment Configuration
- Starter Template Setup
- Developer Ready Structure
'''
        )

    # BACKEND TEMPLATE SELECTION

    if backend.lower() == "fastapi":

        backend_template = os.path.join(

            BASE_DIR,
            "templates",
            "fastapi",
            "main.py"

        )

        backend_file_name = "main.py"

    elif backend.lower() == "node":

        backend_template = os.path.join(

            BASE_DIR,
            "templates",
            "node",
            "server.js"

        )

        backend_file_name = "server.js"

    else:

        backend_template = os.path.join(

            BASE_DIR,
            "templates",
            "fastapi",
            "main.py"

        )

        backend_file_name = "main.py"

    backend_content = read_template(
        backend_template
    )

    backend_main = os.path.join(

        project_path,

        "backend",

        backend_file_name

    )

    with open(backend_main, "w", encoding="utf-8") as file:

        file.write(
            backend_content
        )

    # NODE PACKAGE.JSON

    if backend.lower() == "node":

        package_template = os.path.join(

            BASE_DIR,
            "templates",
            "node",
            "package.json"

        )

        package_content = read_template(
            package_template
        )

        package_file = os.path.join(

            project_path,

            "backend",

            "package.json"

        )

        with open(package_file, "w", encoding="utf-8") as file:

            file.write(
                package_content
            )

    # REQUIREMENTS FILE

    if backend.lower() == "fastapi":

        requirements = os.path.join(

            project_path,

            "backend",

            "requirements.txt"

        )

        with open(requirements, "w", encoding="utf-8") as file:

            file.write(

                "fastapi\nuvicorn"

            )

    # FRONTEND TEMPLATE

    frontend_template = os.path.join(

        BASE_DIR,

        "templates",

        "react",

        "App.jsx"

    )

    frontend_content = read_template(
        frontend_template
    )

    frontend_content = frontend_content.replace(

        "{{PROJECT_NAME}}",

        project_name

    )

    frontend_app = os.path.join(

        project_path,

        "frontend",

        "App.jsx"

    )

    with open(frontend_app, "w", encoding="utf-8") as file:

        file.write(
            frontend_content
        )

    # GITIGNORE FILE

    gitignore_template = os.path.join(

        BASE_DIR,

        "templates",

        "gitignore.txt"

    )

    gitignore_content = read_template(
        gitignore_template
    )

    gitignore_file = os.path.join(

        project_path,

        ".gitignore"

    )

    with open(gitignore_file, "w", encoding="utf-8") as file:

        file.write(
            gitignore_content
        )

    # ENV FILE

    env_template = os.path.join(

        BASE_DIR,

        "templates",

        "env.txt"

    )

    env_content = read_template(
        env_template
    )

    env_file = os.path.join(

        project_path,

        ".env"

    )

    with open(env_file, "w", encoding="utf-8") as file:

        file.write(
            env_content
        )

    # DATABASE CONFIG

    if database.lower() == "postgresql":

        database_file = os.path.join(

            project_path,

            "backend",

            "database.py"

        )

        with open(database_file, "w", encoding="utf-8") as file:

            file.write(

'''from sqlalchemy import create_engine

DATABASE_URL = "postgresql://postgres:password@localhost/db"
'''
            )

    # AUTH TEMPLATE

    if project_type == "Auth API Starter":

        auth_template = os.path.join(

            BASE_DIR,

            "templates",

            "fastapi",

            "auth.py"

        )

        auth_content = read_template(
            auth_template
        )

        auth_file = os.path.join(

            project_path,

            "backend",

            "auth.py"

        )

        with open(auth_file, "w", encoding="utf-8") as file:

            file.write(
                auth_content
            )

    # DOCKERFILE

    dockerfile = os.path.join(

        project_path,

        "Dockerfile"

    )

    with open(dockerfile, "w", encoding="utf-8") as file:

        file.write(

'''FROM python:3.11

WORKDIR /app

COPY . .

RUN pip install -r requirements.txt

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
'''
        )

    # DOCKER COMPOSE

    docker_compose = os.path.join(

        project_path,

        "docker-compose.yml"

    )

    with open(docker_compose, "w", encoding="utf-8") as file:

        file.write(

'''version: "3"

services:

  app:

    build: .

    ports:

      - "8000:8000"
'''
        )


   
    # ZIP FILE

    zip_path = shutil.make_archive(

        project_path,

        'zip',

        project_path

    )

    return zip_path



