function App() {

    return (

        <div style={{

            padding: "40px",

            fontFamily: "Arial"

        }}>

            <h1>hxhg</h1>

            <p>Generated by DevForge</p>

        </div>

    )

}

export default App